language: python
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"
before_install:
  - pip install poetry tox-travis
install:
  - poetry install --verbose
script: tox
after_success:
  - codecov
